import { seedProduct } from './product-seed.types';

export const seedCatalogA = [
  seedProduct({
    id: 'seed-wildflower-favor-kit',
    sku: 'ECO-PLANT-001',
    name: 'Mini Wildflower Seed Favor Kit',
    shortDescription:
      'A plantable favor that turns every thank-you into native blooms.',
    description:
      'A recycled-paper seed packet filled with a pollinator-friendly wildflower mix and finished with a personalized event label. Packed without plastic in a recycled kraft sleeve for wedding tables, birthdays, and thoughtful guest gifts.',
    category: 'Plantable Gifts',
    occasions: ['wedding', 'birthday'],
    priceCents: 1400,
    stockQuantity: 84,
    personalizationAvailable: true,
    ecoScore: 96,
    imageFile: 'weddings.jpg',
    imageAlt: 'Personalized wildflower seed favors arranged for a celebration',
    featuredRank: 1,
  }),
  seedProduct({
    id: 'seed-basil-grow-pot',
    sku: 'ECO-PLANT-002',
    name: 'Basil Grow Pot',
    shortDescription:
      'A compact herb-growing gift with a compostable coir pot.',
    description:
      'This ready-to-grow kit pairs organic basil seeds with a coconut-coir pot and peat-free growing disc. The paper band can carry a name, date, or short message, while the entire pack is recyclable or compostable.',
    category: 'Plantable Gifts',
    occasions: ['birthday', 'corporate'],
    priceCents: 1800,
    stockQuantity: 42,
    personalizationAvailable: true,
    ecoScore: 94,
    imageFile: 'personalization-preview.jpg',
    imageAlt: 'Small personalized basil growing kit in natural packaging',
    featuredRank: 7,
  }),
  seedProduct({
    id: 'seed-succulent-cork-planter',
    sku: 'ECO-PLANT-003',
    name: 'Succulent Cork Planter',
    shortDescription: 'A living desk gift set in renewable natural cork.',
    description:
      'A low-care succulent arrives in a renewable cork planter with a reusable care card. Add a recipient name or company message to the removable paper wrap for a useful wedding, birthday, or team keepsake.',
    category: 'Plantable Gifts',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 2600,
    stockQuantity: 6,
    personalizationAvailable: true,
    ecoScore: 91,
    imageFile: 'corporate.jpg',
    imageAlt:
      'Succulent in a cork planter styled as an eco-conscious desk gift',
    featuredRank: 10,
  }),
  seedProduct({
    id: 'seed-paper-thank-you-cards',
    sku: 'ECO-PLANT-004',
    name: 'Seed Paper Thank-You Cards',
    shortDescription:
      'Personalized notes that can be planted after the celebration.',
    description:
      'A set of twelve handmade seed-paper cards printed with water-based ink. Personalize the front and inside message, then invite recipients to plant the card and grow herbs instead of sending paper to landfill.',
    category: 'Plantable Gifts',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 2400,
    stockQuantity: 115,
    personalizationAvailable: true,
    ecoScore: 98,
    imageFile: 'personalization-preview.jpg',
    imageAlt: 'Personalized plantable thank-you cards with botanical details',
    featuredRank: 4,
  }),
  seedProduct({
    id: 'seed-pollinator-seed-bombs',
    sku: 'ECO-PLANT-005',
    name: 'Pollinator Seed Bomb Trio',
    shortDescription:
      'Three clay seed balls made to support bees and butterflies.',
    description:
      'Locally made clay-and-compost seed balls contain a seasonal mix of nectar-rich flowers. They arrive in a recycled card box with simple planting instructions and no plastic components.',
    category: 'Plantable Gifts',
    occasions: ['birthday', 'corporate'],
    priceCents: 1600,
    stockQuantity: 0,
    personalizationAvailable: false,
    ecoScore: 97,
    imageFile: 'birthdays.jpg',
    imageAlt: 'Three pollinator seed balls in a recycled gift box',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-soy-keepsake-candle',
    sku: 'ECO-HOME-001',
    name: 'Hand-Poured Soy Keepsake Candle',
    shortDescription:
      'A softly scented soy candle poured into a reusable amber jar.',
    description:
      'Small-batch soy wax, a cotton wick, and phthalate-free fragrance create a cleaner-burning keepsake. Personalize the paper label with names, a date, or a message; the glass jar can be reused once the candle is finished.',
    category: 'Artisan Home',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 3200,
    stockQuantity: 58,
    personalizationAvailable: true,
    ecoScore: 89,
    imageFile: 'candle.jpeg',
    imageAlt: 'Hand-poured soy candle in a personalized reusable amber jar',
    featuredRank: 2,
  }),
  seedProduct({
    id: 'seed-linen-keepsake-pouch',
    sku: 'ECO-HOME-002',
    name: 'Woven Linen Keepsake Pouch',
    shortDescription:
      'A reusable linen pouch for favors, jewelry, or small treasures.',
    description:
      'Made from a linen and recycled-cotton blend, this drawstring pouch replaces single-use favor packaging. Add a name, initials, or event date in your chosen font and color for a practical keepsake.',
    category: 'Artisan Home',
    occasions: ['wedding', 'birthday'],
    priceCents: 1900,
    stockQuantity: 73,
    personalizationAvailable: true,
    ecoScore: 92,
    imageFile: 'linen-throw.jpeg',
    imageAlt: 'Natural woven linen keepsake pouch with personalized lettering',
    featuredRank: 9,
  }),
  seedProduct({
    id: 'seed-reclaimed-photo-stand',
    sku: 'ECO-HOME-003',
    name: 'Reclaimed Wood Photo Stand',
    shortDescription:
      'A minimal photo holder handcrafted from rescued timber offcuts.',
    description:
      'Each solid-wood block is shaped from workshop offcuts, sanded by hand, and finished with plant-based oil. It holds a favorite photo or place card and includes an engraved personalization option.',
    category: 'Artisan Home',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 2800,
    stockQuantity: 19,
    personalizationAvailable: true,
    ecoScore: 95,
    imageFile: 'quiet-comfort.jpeg',
    imageAlt: 'Minimal reclaimed wood photo stand in a calm home setting',
    featuredRank: 6,
  }),
  seedProduct({
    id: 'seed-coconut-trinket-bowl',
    sku: 'ECO-HOME-004',
    name: 'Coconut Shell Trinket Bowl',
    shortDescription:
      'A polished catch-all bowl made from reclaimed coconut shell.',
    description:
      'Discarded coconut shells are cleaned, shaped, and polished with food-safe coconut oil by local makers. Natural variation makes every bowl unique, while recycled-card packaging keeps the gift low waste.',
    category: 'Artisan Home',
    occasions: ['wedding', 'birthday'],
    priceCents: 2200,
    stockQuantity: 7,
    personalizationAvailable: false,
    ecoScore: 93,
    imageFile: 'storage-set.png',
    imageAlt: 'Polished coconut shell trinket bowl for a sustainable home gift',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-mini-bud-vase',
    sku: 'ECO-HOME-005',
    name: 'Hand-Thrown Mini Bud Vase',
    shortDescription:
      'A small artisan vase made with locally sourced stoneware clay.',
    description:
      'Hand-thrown in small batches and glazed with a lead-free finish, this bud vase celebrates the marks of its maker. It ships in molded recycled pulp with a maker story card and care guide.',
    category: 'Artisan Home',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 3800,
    stockQuantity: 22,
    personalizationAvailable: false,
    ecoScore: 87,
    imageFile: 'landing-hero.jpg',
    imageAlt: 'Hand-thrown miniature stoneware bud vase with a simple stem',
    featuredRank: 12,
  }),
] as const;
