import { seedProduct } from './product-seed.types';

export const seedCatalogC = [
  seedProduct({
    id: 'seed-recycled-paper-journal',
    sku: 'ECO-DESK-001',
    name: 'Recycled Paper Journal',
    shortDescription:
      'A lay-flat notebook made with post-consumer paper and soy ink.',
    description:
      'One hundred and sixty ruled pages are bound in a durable recycled-board cover with cotton thread. Personalize the cover for client, employee, birthday, or planning gifts without adding plastic.',
    category: 'Corporate & Desk',
    occasions: ['birthday', 'corporate'],
    priceCents: 2700,
    stockQuantity: 76,
    personalizationAvailable: true,
    ecoScore: 92,
    imageFile: 'corporate.jpg',
    imageAlt: 'Recycled paper journal with a personalized natural cover',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-cork-desk-organizer',
    sku: 'ECO-DESK-002',
    name: 'Cork Desk Organizer',
    shortDescription:
      'A modular organizer cut from renewable and recyclable cork.',
    description:
      'Three nested cork trays keep pens, notes, and small devices organized while protecting the desk surface. A laser-etched name or logo provides durable personalization with no vinyl or plastic label.',
    category: 'Corporate & Desk',
    occasions: ['birthday', 'corporate'],
    priceCents: 4200,
    stockQuantity: 23,
    personalizationAvailable: true,
    ecoScore: 90,
    imageFile: 'corporate.jpg',
    imageAlt: 'Modular natural cork organizer on a tidy work desk',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-plantable-pencil-set',
    sku: 'ECO-DESK-003',
    name: 'Plantable Pencil Set',
    shortDescription:
      'Five graphite pencils with herb seeds tucked into each end.',
    description:
      'FSC-certified wood pencils replace erasers with biodegradable seed capsules for basil, mint, and tomato. Use them down, plant the labeled ends, and grow a small windowsill garden.',
    category: 'Corporate & Desk',
    occasions: ['birthday', 'corporate'],
    priceCents: 1500,
    stockQuantity: 132,
    personalizationAvailable: true,
    ecoScore: 97,
    imageFile: 'personalization-preview.jpg',
    imageAlt: 'Set of five plantable pencils in a recycled paper sleeve',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-conference-bottle',
    sku: 'ECO-DESK-004',
    name: 'Reusable Conference Bottle',
    shortDescription:
      'An insulated steel bottle designed for daily refill and reuse.',
    description:
      'A 500 ml food-grade stainless-steel bottle keeps drinks cool and replaces disposable event bottles. Durable laser engraving supports names or company branding, and the pack is fully recyclable.',
    category: 'Corporate & Desk',
    occasions: ['corporate'],
    priceCents: 4800,
    stockQuantity: 49,
    personalizationAvailable: true,
    ecoScore: 88,
    imageFile: 'storage-set.png',
    imageAlt: 'Insulated reusable conference bottle in recyclable packaging',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-upcycled-tech-sleeve',
    sku: 'ECO-DESK-005',
    name: 'Upcycled Felt Tech Sleeve',
    shortDescription:
      'A protective tablet sleeve made from recovered textile fibers.',
    description:
      'Dense upcycled felt cushions tablets and small laptops while a cork strap keeps the profile clean. The sleeve is stitched locally and accepts an embroidered name or short company mark.',
    category: 'Corporate & Desk',
    occasions: ['birthday', 'corporate'],
    priceCents: 5400,
    stockQuantity: 3,
    personalizationAvailable: true,
    ecoScore: 86,
    imageFile: 'corporate.jpg',
    imageAlt: 'Upcycled felt tablet sleeve with a natural cork closure',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-wooden-milestone-tokens',
    sku: 'ECO-FAVOR-001',
    name: 'Wooden Milestone Tokens',
    shortDescription:
      'Reusable engraved markers for birthdays and family milestones.',
    description:
      'A set of twelve smooth FSC-certified wood tokens records meaningful dates without disposable decorations. Choose personalized wording and store them in the included recycled cotton pouch.',
    category: 'Celebration Favors',
    occasions: ['birthday'],
    priceCents: 3300,
    stockQuantity: 29,
    personalizationAvailable: true,
    ecoScore: 91,
    imageFile: 'birthdays.jpg',
    imageAlt: 'Engraved wooden milestone tokens in a recycled cotton pouch',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-natural-crayon-set',
    sku: 'ECO-FAVOR-002',
    name: 'Natural Crayon Celebration Set',
    shortDescription:
      'Twelve bright crayons made with beeswax and plant-based color.',
    description:
      'Chunky handmade crayons use responsibly sourced beeswax and mineral or plant-based pigments. A reusable recycled-card box can be personalized for party favors and creative birthday gifts.',
    category: 'Celebration Favors',
    occasions: ['birthday'],
    priceCents: 2300,
    stockQuantity: 61,
    personalizationAvailable: true,
    ecoScore: 87,
    imageFile: 'birthdays.jpg',
    imageAlt: 'Colorful natural crayons in a personalized recycled card box',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-fabric-gift-wrap',
    sku: 'ECO-FAVOR-003',
    name: 'Reusable Fabric Gift Wrap',
    shortDescription:
      'A reversible cotton wrap inspired by the art of furoshiki.',
    description:
      'A generously sized wrap made from rescued cotton fabric turns gift packaging into part of the present. Illustrated folding instructions show several ways to reuse it for bottles, boxes, and everyday carrying.',
    category: 'Celebration Favors',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 2500,
    stockQuantity: 44,
    personalizationAvailable: false,
    ecoScore: 96,
    imageFile: 'linen-throw.jpeg',
    imageAlt: 'Reusable patterned fabric wrapped around a thoughtful gift',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-jute-favor-bag',
    sku: 'ECO-FAVOR-004',
    name: 'Personalized Jute Favor Bag',
    shortDescription:
      'A sturdy reusable favor bag with custom text and artwork.',
    description:
      'Natural jute and a soft recycled-cotton lining create a durable alternative to disposable gift bags. Add names, a date, free-form text, or uploaded artwork using the product personalizer.',
    category: 'Celebration Favors',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 2000,
    stockQuantity: 88,
    personalizationAvailable: true,
    ecoScore: 93,
    imageFile: 'weddings.jpg',
    imageAlt: 'Personalized natural jute favor bag for an event guest',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-glass-keepsake-jar',
    sku: 'ECO-FAVOR-005',
    name: 'Recycled Glass Keepsake Jar',
    shortDescription: 'A multipurpose recycled-glass jar with a bamboo lid.',
    description:
      'The softly tinted jar is made with high recycled-glass content and topped with a renewable bamboo lid. Use it for sweets, tea, desk storage, or keepsakes, with an optional personalized paper label.',
    category: 'Celebration Favors',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 3000,
    stockQuantity: 0,
    personalizationAvailable: true,
    ecoScore: 90,
    imageFile: 'storage-set.png',
    imageAlt: 'Recycled glass keepsake jar with a fitted bamboo lid',
    featuredRank: null,
  }),
] as const;
