import { seedProduct } from './product-seed.types';

export const seedCatalogB = [
  seedProduct({
    id: 'seed-organic-matcha-set',
    sku: 'ECO-FOOD-001',
    name: 'Organic Matcha Tea Set',
    shortDescription:
      'Ceremonial matcha with a bamboo whisk and reusable tea tin.',
    description:
      'A mindful tea ritual featuring certified organic matcha, a hand-cut bamboo whisk, and a recyclable steel tin. The gift note and tin band can be personalized for celebrations or thoughtful team rewards.',
    category: 'Food & Drink',
    occasions: ['birthday', 'corporate'],
    priceCents: 5200,
    stockQuantity: 31,
    personalizationAvailable: true,
    ecoScore: 88,
    imageFile: 'tea-set.jpeg',
    imageAlt: 'Organic matcha tea set with bamboo whisk and reusable tin',
    featuredRank: 3,
  }),
  seedProduct({
    id: 'seed-fairtrade-chai-taster',
    sku: 'ECO-FOOD-002',
    name: 'Fairtrade Chai Taster',
    shortDescription:
      'Three aromatic loose-leaf chai blends in refillable tins.',
    description:
      'Ethically sourced tea and whole spices are blended in small batches and packed in three reusable mini tins. A recycled paper tasting guide explains each origin, steeping method, and flavor profile.',
    category: 'Food & Drink',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 3400,
    stockQuantity: 47,
    personalizationAvailable: true,
    ecoScore: 86,
    imageFile: 'tea-set.jpeg',
    imageAlt: 'Fairtrade loose-leaf chai tasting tins with spices',
    featuredRank: 11,
  }),
  seedProduct({
    id: 'seed-glass-infuser-bottle',
    sku: 'ECO-FOOD-003',
    name: 'Recycled Glass Infuser Bottle',
    shortDescription: 'A reusable bottle for fruit water and loose-leaf tea.',
    description:
      'Made with recycled borosilicate glass, a stainless-steel infuser, and a protective cork sleeve. Add a name or company mark to the sleeve for an everyday gift that helps replace disposable drink bottles.',
    category: 'Food & Drink',
    occasions: ['birthday', 'corporate'],
    priceCents: 4600,
    stockQuantity: 5,
    personalizationAvailable: true,
    ecoScore: 90,
    imageFile: 'storage-set.png',
    imageAlt: 'Recycled glass infuser bottle with a natural cork sleeve',
    featuredRank: 8,
  }),
  seedProduct({
    id: 'seed-bamboo-travel-cup',
    sku: 'ECO-FOOD-004',
    name: 'Bamboo Travel Cup',
    shortDescription:
      'A lightweight reusable cup wrapped in fast-growing bamboo fiber.',
    description:
      'This 350 ml travel cup combines a food-safe stainless-steel interior with a bamboo-fiber outer shell and splash-resistant lid. Laser personalization makes it a useful guest or employee gift.',
    category: 'Food & Drink',
    occasions: ['birthday', 'corporate'],
    priceCents: 3900,
    stockQuantity: 64,
    personalizationAvailable: true,
    ecoScore: 85,
    imageFile: 'corporate.jpg',
    imageAlt: 'Reusable bamboo travel cup presented as a corporate gift',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-local-honey-dipper',
    sku: 'ECO-FOOD-005',
    name: 'Local Honey & Wooden Dipper',
    shortDescription:
      'Small-batch wildflower honey with a responsibly sourced wood dipper.',
    description:
      'A reusable glass jar of locally harvested wildflower honey is paired with an untreated wooden dipper. The beekeeper story and pollinator impact are printed on recycled paper with a personalizable gift band.',
    category: 'Food & Drink',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 2900,
    stockQuantity: 38,
    personalizationAvailable: true,
    ecoScore: 91,
    imageFile: 'weddings.jpg',
    imageAlt: 'Local wildflower honey jar with a wooden dipper and gift band',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-botanical-soap-pair',
    sku: 'ECO-WELL-001',
    name: 'Botanical Soap Pair',
    shortDescription:
      'Two cold-process soaps made with plant oils and garden botanicals.',
    description:
      'Hand-cut bars use olive, coconut, and rice-bran oils with natural botanical color and essential-oil scent. The pair is wrapped in compostable glassine and recycled card with no plastic.',
    category: 'Wellbeing',
    occasions: ['wedding', 'birthday', 'corporate'],
    priceCents: 2400,
    stockQuantity: 91,
    personalizationAvailable: true,
    ecoScore: 94,
    imageFile: 'quiet-comfort.jpeg',
    imageAlt: 'Pair of handmade botanical soaps in compostable wrapping',
    featuredRank: 5,
  }),
  seedProduct({
    id: 'seed-lavender-eye-pillow',
    sku: 'ECO-WELL-002',
    name: 'Lavender Eye Pillow',
    shortDescription:
      'A calming linen eye pillow filled with flaxseed and dried lavender.',
    description:
      'A removable linen-and-organic-cotton cover surrounds a natural flaxseed and lavender filling. Add initials or a short word to the cover, which can be washed and reused for rest or meditation.',
    category: 'Wellbeing',
    occasions: ['birthday', 'corporate'],
    priceCents: 3100,
    stockQuantity: 26,
    personalizationAvailable: true,
    ecoScore: 92,
    imageFile: 'linen-throw.jpeg',
    imageAlt: 'Natural linen lavender eye pillow for relaxation',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-natural-bath-salts',
    sku: 'ECO-WELL-003',
    name: 'Natural Bath Salt Vial',
    shortDescription:
      'Mineral bath salts with dried petals in a refillable glass vial.',
    description:
      'Mineral-rich sea salt, Epsom salt, and locally dried flower petals are blended without synthetic dye. The corked glass vial can be refilled, and the recycled label can carry a custom message.',
    category: 'Wellbeing',
    occasions: ['wedding', 'birthday'],
    priceCents: 1700,
    stockQuantity: 4,
    personalizationAvailable: true,
    ecoScore: 90,
    imageFile: 'candle.jpeg',
    imageAlt: 'Floral mineral bath salts in a refillable corked glass vial',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-bamboo-comb',
    sku: 'ECO-WELL-004',
    name: 'Bamboo Comb Keepsake',
    shortDescription: 'A smooth wide-tooth comb made from fast-growing bamboo.',
    description:
      'The hand-finished bamboo comb is anti-static, durable, and supplied in a recycled cotton sleeve. Optional engraving adds a name or date without adding ink, labels, or disposable decoration.',
    category: 'Wellbeing',
    occasions: ['wedding', 'birthday'],
    priceCents: 2100,
    stockQuantity: 54,
    personalizationAvailable: true,
    ecoScore: 95,
    imageFile: 'personalization-preview.jpg',
    imageAlt: 'Engraved bamboo comb in a recycled cotton sleeve',
    featuredRank: null,
  }),
  seedProduct({
    id: 'seed-organic-spa-cloths',
    sku: 'ECO-WELL-005',
    name: 'Organic Cotton Spa Cloth Set',
    shortDescription:
      'Three washable face cloths tied with a reusable cotton ribbon.',
    description:
      'Soft GOTS-certified organic cotton cloths replace disposable wipes in daily routines. The set uses low-impact dyes, a reusable cotton ribbon, and a recycled care card with optional personalized text.',
    category: 'Wellbeing',
    occasions: ['birthday', 'corporate'],
    priceCents: 3600,
    stockQuantity: 18,
    personalizationAvailable: true,
    ecoScore: 93,
    imageFile: 'quiet-comfort.jpeg',
    imageAlt: 'Organic cotton spa cloth set tied with a reusable ribbon',
    featuredRank: null,
  }),
] as const;
